rmtpp:
  cat_sizes: [22]
  emb_dims: [20]
  marker_weights: [0.07]
  time_loss_weight: 0.1
  input_size: 21
  lstm_hidden_size: 32
  hidden_size: 16
  n_num_feats: 1
  w: 0.15
  w_trainable: False
  time_scale: 0.01
  max_seq_len: 25
  dropout: 0.2
  integration_end: 1400
rnnsm:
  cat_sizes: [22]
  emb_dims: [20]
  input_size: 21
  lstm_hidden_size: 32
  hidden_size: 16
  n_num_feats: 1
  w: 0.15
  w_trainable: False
  time_scale: 0.1
  max_seq_len: 10
  dropout: 0.2
  integration_end: 1400
training:
  lr: 0.0001
  n_epochs: 30
  batch_size: 200
  model_path: model.pth
  model: rnnsm
task:
  activity_start: 1375
  prediction_start: 1380
  prediction_end: 1388
