rmtpp:
  cat_sizes: [7]
  emb_dims: [12]
  marker_weights: [1.0]
  input_size: 13
  hidden_size: 13
  n_num_feats: 1
  w: 0.15
  time_scale: 0.2
  dropout: 0.2
rnnsm:
  cat_sizes: [7]
  emb_dims: [13]
  input_size: 13
  hidden_size: 13
  n_num_feats: 1
  w: 0.15
  time_scale: 0.2
  dropout: 0.2
training:
  lr: 0.01
  n_epochs: 10
  
