rmtpp:
  cat_sizes: [22]
  n_num_feats: 1
  emb_dims: [20]
  marker_weights: [0.07]
  time_loss_weight: 0.01
  input_size: 21
  lstm_hidden_size: 32
  hidden_size: 16
  dropout: 0.2
  w: 0.15
  w_trainable: False
  time_scale: 1
  max_seq_len: 25
  integration_end: 1400
rnnsm:
  cat_sizes: [22]
  n_num_feats: 1
  emb_dims: [20]
  input_size: 21
  lstm_hidden_size: 32
  hidden_size: 16
  dropout: 0.2
  w: 0.2
  w_trainable: False
  max_seq_len: 30
  integration_end: 1400
  prediction_start: ${globals.prediction_start}
  time_scale: 0.1
grobformer:
  cat_size: 22
  model_dim: 32
  hidden_dim: 64
  n_head: 4
  n_layers: 1
  d_k: 8
  d_v: 8
  w: 0.2
  dropout: 0.1
  w_trainable: False
  integration_end: 1400
  prediction_start: ${globals.prediction_start}
  time_scale: 0.1
training:
  lr: 0.001
  n_epochs: 30
  batch_size: 100
  model_path: model.pth
  model: rnnsm
  validate_by: rmse
testing:
  model_path: model.pth
  model: grobformer
globals:
  activity_start: 1380
  prediction_start: 1386
  prediction_end: 1388
  dobavka: 10
  drop_ratio: 0.7
  padding_id: 0
