rmtpp:
  cat_sizes: [7]
  emb_dims: [12]
  marker_weights: [0.07]
  input_size: 13
  lstm_hidden_size: 30
  hidden_size: 15
  n_num_feats: 1
  w: 0.15
  time_scale: 0.1
  max_seq_len: 50
  dropout: 0.2
  integration_steps: 500
rnnsm:
  cat_sizes: [7]
  emb_dims: [15]
  input_size: 16
  lstm_hidden_size: 30
  hidden_size: 15
  n_num_feats: 1
  w: 0.15
  time_scale: 0.1
  max_seq_len: 50
  dropout: 0.2
  integration_steps: 500
training:
  lr: 0.001
  n_epochs: 10
  batch_size: 200
