rmtpp:
  cat_sizes: [22]
  emb_dims: [20]
  marker_weights: [0.07]
  time_loss_weight: 0.1
  input_size: 21
  lstm_hidden_size: 32
  hidden_size: 16
  n_num_feats: 1
  w: 0.15
  time_scale: 0.002
  max_seq_len: 25
  dropout: 0.2
  integration_steps: 500
rnnsm:
  cat_sizes: [22]
  emb_dims: [20]
  input_size: 21
  lstm_hidden_size: 32
  hidden_size: 16
  n_num_feats: 1
  w: 0.15
  time_scale: 0.1
  max_seq_len: 25
  dropout: 0.2
  integration_steps: 500
training:
  lr: 0.001
  n_epochs: 30
  batch_size: 200
